### ISSUE TITLE
No modal dialog

### ISSUE THREAD

**Issue by jospoortvliet** [pbek/ownbackup#2]
When starting a backup, the app asks first if you are sure you want to do that.

![test6](https://cloud.githubusercontent.com/assets/551757/9246740/d438ebc2-41ad-11e5-968f-e060dc0f896e.png)

I think it would be better to 'just' offer a cancel option and/or a delete option for backups.
See also https://doc.owncloud.org/server/8.1/developer_manual/general/codingguidelines.html#user-interface

**Comment by pbek** [comment]
Do you want to know why I wrote ownbackup in the first place? :)
...because there was a (non-descriptive) button in the iOS news app, that marked all my news items as "read" when I accidently pressed it. There was no confirmation message to warn me about what is going to happen. (of course restoring the news tables is only possible because I'm the only user on my OC system)

I think marking all messages as read as well as creating manual backups are not things one does very often and may not want to do by accident (the latter because you must not close the browser window when creating backups on the frontend).

**Comment by jospoortvliet** [comment]
@pbek that is quite a serious flaw in the iOS news app then ;-)

It should certainly offer an undo option for that.

**Comment by pbek** [comment]
Currently (with the current news database table layout) it can't be undone. So I wrote ownbackup. :)

Starting a backup in the foreground is a serious task, thus I wanted the confirmation (as long it isn't done in the background).

**Comment by pbek** [comment]
@jospoortvliet if you want you can file a feature request: "Do manual backups in background"
Maybe then the confirmation could go. ;)

**Comment by jospoortvliet** [comment]
Well, that honestly seems like a technical detail (a big one, technically speaking - but for the user experience it is a detail).

**Comment by pbek** [comment]
I will close this issue until someone comes up with it again. ;)
